# Generated by Django 5.1.3 on 2024-11-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visua_org_id', models.IntegerField(blank=True, null=True)),
                ('visua_dest_id', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('y_org', models.IntegerField(blank=True, null=True)),
                ('y_dest', models.IntegerField(blank=True, null=True)),
                ('x_org', models.IntegerField(blank=True, null=True)),
                ('x_dest', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'arrow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('type_category', models.CharField(blank=True, max_length=1, null=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryObject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('contact_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category_object',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('address_work', models.TextField(blank=True, null=True)),
                ('zip_code_work', models.CharField(blank=True, max_length=50, null=True)),
                ('city_work', models.CharField(blank=True, max_length=50, null=True)),
                ('code_building', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('email_work', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_work', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_cel', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_cel_work', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_fax_work', models.CharField(blank=True, max_length=50, null=True)),
                ('date_birth', models.DateTimeField(blank=True, null=True)),
                ('date_nameday', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
                ('responsable', models.TextField(blank=True, null=True)),
                ('associate', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('site_web', models.CharField(blank=True, max_length=250, null=True)),
                ('site_web_work', models.CharField(blank=True, max_length=50, null=True)),
                ('schedules_work', models.CharField(blank=True, max_length=50, null=True)),
                ('date_delete', models.DateTimeField(blank=True, null=True)),
                ('is_visua', models.IntegerField(blank=True, null=True)),
                ('is_synch', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('contact_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contact_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Decisional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('type_decisional', models.CharField(blank=True, max_length=255, null=True)),
                ('scoring', models.IntegerField(blank=True, null=True)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('solution', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'decisional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abscon', models.TextField(blank=True, null=True)),
                ('formulation', models.TextField(blank=True, null=True)),
                ('measurable', models.TextField(blank=True, null=True)),
                ('resource', models.TextField(blank=True, null=True)),
                ('ecological', models.TextField(blank=True, null=True)),
                ('circumstantial', models.TextField(blank=True, null=True)),
                ('realistic', models.TextField(blank=True, null=True)),
                ('exciting', models.TextField(blank=True, null=True)),
                ('reward', models.TextField(blank=True, null=True)),
                ('project_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'goal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('is_ged', models.IntegerField(blank=True, null=True)),
                ('date_delete', models.DateTimeField(blank=True, null=True)),
                ('is_visua', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('contain', models.TextField(blank=True, null=True)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('date_delete', models.DateTimeField(blank=True, null=True)),
                ('is_visua', models.IntegerField(blank=True, null=True)),
                ('color_back', models.CharField(blank=True, max_length=255, null=True)),
                ('type_note', models.CharField(blank=True, max_length=255, null=True)),
                ('is_rich', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'note',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(blank=True, max_length=255, null=True)),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('second_key', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'param',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('filename', models.TextField(blank=True, null=True)),
                ('color_back', models.CharField(blank=True, max_length=255, null=True)),
                ('date_delete', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'picture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_projet', models.CharField(blank=True, max_length=1, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('price_projected', models.FloatField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_delete', models.DateTimeField(blank=True, null=True)),
                ('is_done', models.IntegerField(blank=True, null=True)),
                ('font', models.CharField(blank=True, max_length=50, null=True)),
                ('color_visua', models.CharField(blank=True, max_length=255, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('date_begin', models.DateTimeField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('note', models.IntegerField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=8, null=True)),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('date_done', models.DateTimeField(blank=True, null=True)),
                ('is_visua', models.IntegerField(blank=True, null=True)),
                ('is_synch', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reminder', models.IntegerField(blank=True, null=True)),
                ('unit_reminder', models.CharField(blank=True, max_length=10, null=True)),
                ('project_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reminder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('contain', models.TextField(blank=True, null=True)),
                ('color_back', models.CharField(blank=True, max_length=255, null=True)),
                ('date_delete', models.DateTimeField(blank=True, null=True)),
                ('color_write', models.CharField(blank=True, max_length=255, null=True)),
                ('font', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sticker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_category', models.CharField(blank=True, max_length=3, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'type_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_project', models.CharField(blank=True, max_length=2, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'type_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visua',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position_x', models.IntegerField(blank=True, null=True)),
                ('position_y', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('date_delete', models.DateTimeField(blank=True, null=True)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('note_id', models.IntegerField(blank=True, null=True)),
                ('link_id', models.IntegerField(blank=True, null=True)),
                ('contact_id', models.IntegerField(blank=True, null=True)),
                ('sticker_id', models.IntegerField(blank=True, null=True)),
                ('picture_id', models.IntegerField(blank=True, null=True)),
                ('action_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'visua',
                'managed': False,
            },
        ),
    ]
